// Code generated by scripts/gen-constants. DO NOT EDIT.
// Edit shared/constants.json at the repo root, then re-run:
//   cd server && go run ./scripts/gen-constants

package shared

const (
	CodeLength         = 6
	GameOverSentinel   = "GAME_OVER"
	MinPhaseSeconds    = 10
	WSEventBoard       = "Board"
	WSEventLeaderboard = "Leaderboard"
	WSEventPlayers     = "Players"
	WSEventStart       = "Start"
	WSEventTime        = "Time"
	WSHandshakeError   = "error"
	WSHandshakeSuccess = "success"
)
