// Code generated by scripts/gen-constants. DO NOT EDIT.
// Edit shared/constants.json at the repo root, then re-run:
//   cd server && go run ./scripts/gen-constants

export const CodeLength = 6;
export const GameOverSentinel = 'GAME_OVER';
export const MinPhaseSeconds = 10;
export const WSEventBoard = 'Board';
export const WSEventLeaderboard = 'Leaderboard';
export const WSEventPlayers = 'Players';
export const WSEventStart = 'Start';
export const WSEventTime = 'Time';
export const WSHandshakeError = 'error';
export const WSHandshakeSuccess = 'success';
