// gen-constants reads shared/constants.json from the repo root and generates
// server/shared/constants.go and client/src/lib/constants.ts.
//
// Run from the server/ directory:
//
//	go run ./scripts/gen-constants
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

func main() {
	data, err := os.ReadFile("../shared/constants.json")
	if err != nil {
		fmt.Fprintf(os.Stderr, "read constants.json: %v\n", err)
		os.Exit(1)
	}

	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		fmt.Fprintf(os.Stderr, "parse constants.json: %v\n", err)
		os.Exit(1)
	}

	keys := make([]string, 0, len(raw))
	for k := range raw {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	if err := writeGo(keys, raw); err != nil {
		fmt.Fprintf(os.Stderr, "write Go: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote shared/constants.go")

	if err := writeTS(keys, raw); err != nil {
		fmt.Fprintf(os.Stderr, "write TS: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote ../client/src/lib/constants.ts")
}

func writeGo(keys []string, raw map[string]any) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by scripts/gen-constants. DO NOT EDIT.\n")
	sb.WriteString("// Edit shared/constants.json at the repo root, then re-run:\n")
	sb.WriteString("//   cd server && go run ./scripts/gen-constants\n\n")
	sb.WriteString("package shared\n\nconst (\n")
	for _, k := range keys {
		switch v := raw[k].(type) {
		case string:
			fmt.Fprintf(&sb, "\t%s = %q\n", k, v)
		case float64:
			fmt.Fprintf(&sb, "\t%s = %d\n", k, int(v))
		}
	}
	sb.WriteString(")\n")
	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		return fmt.Errorf("gofmt: %w", err)
	}
	return os.WriteFile("shared/constants.go", formatted, 0644)
}

func writeTS(keys []string, raw map[string]any) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by scripts/gen-constants. DO NOT EDIT.\n")
	sb.WriteString("// Edit shared/constants.json at the repo root, then re-run:\n")
	sb.WriteString("//   cd server && go run ./scripts/gen-constants\n\n")
	for _, k := range keys {
		switch v := raw[k].(type) {
		case string:
			fmt.Fprintf(&sb, "export const %s = '%s';\n", k, v)
		case float64:
			fmt.Fprintf(&sb, "export const %s = %d;\n", k, int(v))
		}
	}
	return os.WriteFile("../client/src/lib/constants.ts", []byte(sb.String()), 0644)
}
